### ISSUE TITLE
Remove closed glycan structures

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/rbd-ace2-contact-analysis#6]
@glass-w  should we remove closed glycan structures from `representative_glycan_structures` since these were not used in the final system?

**Comment by glass-w** [comment]
Yes! The only reason these weren't used were due to steric clashes. From Elisa's analysis both populations would be present so we only chose the ones that fitted best.

**Comment by glass-w** [comment]
Addressed in #7
